# Additional distribution plots regarding character degree and strength.
# Unlike the files generated by the main script, these combine unfiltered
# and filtered results in the same plot.
# 
# Vincent Labatut
# 12/2021
#
# setwd("~/eclipse/workspaces/Networks/NaNet")
# setwd("C:/Users/Vincent/Eclipse/workspaces/Networks/NaNet")
# source("src/post/description/deg_plots.R")
###############################################################################
SERIES <- "Thorgal"
source("src/common/_include.R")
start.rec.log(text="DegDistr")




###############################################################################
# note: result of Clauset et al.'s method (already computed in the main script)
# TODO: automate the retrieval of this information
laws <- c()
# unfiltered 
laws["Unfiltered-degree"] <- "good"
laws["Unfiltered-strength-occurrences"] <- "no fit"
laws["Unfiltered-strength-duration"] <- "no fit"
# filtered 
laws["Filtered-degree"] <- "no fit"
laws["Filtered-strength-occurrences"] <- "no fit"
laws["Filtered-strength-duration"] <- "truncated"




###############################################################################
# distribution plots
tlog(0,"Producing degree & strength distribution plots")

# load corpus stats
data <- read.corpus.data()
# get filtered characters
filt.names <- data$char.stats[data$char.stats[,COL_FILTER]=="Discard",COL_NAME]
if(length(filt.names)==0) stop("Empty list of filtered characters")
idx.keep <- which(data$char.stats[,COL_FILTER]=="Keep")

# loop params
meass <- c(MEAS_DEGREE,MEAS_STRENGTH)
pal <- ATT_COLORS_FILT[c("Discard","Keep")]

# load numbers of occurrences of characters
file <- get.path.stats.corpus(object="characters", subfold="unfiltered", pref="_char_stats.csv")
sce.nbr <- read.csv(file=file, header=TRUE, check.names=FALSE, stringsAsFactors=FALSE)[,COL_SCENES]

# process each measure
for(meas in meass)
{	tlog(2,"Dealing with measure ",meas)
	if(meas==MEAS_STRENGTH)
		wts <- c("duration","occurrences")
	else
		wts <- c("none")

	for(wt in wts)
	{	tlog(4,"Dealing with weight \"",wt,"\"")
		
		# load precomputed data
		data <- list()
		# unfiltered
		file <- get.path.stat.table(object="nodes", mode="scenes", net.type="static", weights=wt, filtered="unfiltered", compare=FALSE)
		tab <- as.matrix(read.csv(file, header=TRUE, check.names=FALSE, row.names=1))
		data[[1]] <- tab[,meas]
		unfilt.idx <- data[[1]] > 0
		data[[1]] <- data[[1]][unfilt.idx]	# remove isolates
#		file <- get.path.stats.comp(mode="scenes", meas.name=meas, weights=if(is.na(wt)) "none" else wt, filtered=FALSE, suf="distr-test_noisolates")
#		test.disc.distr(data[[1]], xlab=paste0("Unfiltered ",ALL_MEASURES[[meas]]$cname," (no isolates)"), return_stats=FALSE, sims=100, plot.file=file)
		# filtered
		file <- get.path.stat.table(object="nodes", mode="scenes", net.type="static", weights=wt, filtered="filtered", compare=FALSE)
		tab <- as.matrix(read.csv(file, header=TRUE, check.names=FALSE, row.names=1))
		data[[2]] <- tab[,meas]
		filt.idx <- data[[2]] > 1
		data[[2]] <- data[[2]][filt.idx]	# remove isolates
		names(data) <- c("Unfiltered","Filtered")
#		file <- get.path.stats.comp(mode="scenes", meas.name=meas, weights=if(is.na(wt)) "none" else wt, filtered=TRUE, suf="distr-test_noisolates")
#		test.disc.distr(data[[2]], xlab=paste0("Unfiltered ",ALL_MEASURES[[meas]]$cname," (no isolates)"), return_stats=FALSE, sims=100, plot.file=file)
		
		# set params
		file <- get.path.stats.topo(net.type="static", mode="scenes", meas.name=meas, weights=wt, filtered="both", suf="ccdf")
		ml <- paste0(ALL_MEASURES[[meas]]$cname, " distribution")
		if(wt!="none")
			ml <- paste0(ml," (",wt,")")
		xl <- paste0(ALL_MEASURES[[meas]]$cname)
		if(wt!="none")
			xl <- paste0(xl," (",wt,")")
	
		# check distribution
		pl <- list()
		for(i in 1:length(data))
		{	power.law <- displ$new(data[[i]])
			est <- estimate_xmin(power.law)
			tmp <- power.law$setXmin(est)
			if(laws[paste0(names(data)[i],"-",meas,if(wt!="none") paste0("-",wt) else "")]=="truncated")
				pl[[i]] <- discpowerexp.fit(x=data[[i]],threshold=power.law$xmin)
			else if(laws[paste0(names(data)[i],"-",meas,if(wt!="none") paste0("-",wt) else "")]=="good")
				pl[[i]] <- power.law
			else
				pl[[i]] <- NA
		}
		print(pl)
		
		# plot distributions
		for(fformat in PLOT_FORMAT)
		{	if(fformat==PLOT_FORMAT_PDF)
				pdf(file=paste0(file,PLOT_FORMAT_PDF), bg="white")
			else if(fformat==PLOT_FORMAT_PNG)
				png(filename=paste0(file,PLOT_FORMAT_PNG), width=800, height=800, units="px", pointsize=20, bg="white")
			par(mar=c(4,4,0,0)+0.1)	# remove the title space Bottom Left Top Right
			plot.ccdf(data=data, main=NA, xlab=xl, ylab="default", log=TRUE, cols=pal, leg=TRUE, leg.title="Characters")
			for(i in 1:2)
			{	if(laws[paste0(names(data)[i],"-",meas,if(wt!="none") paste0("-",wt) else "")]=="truncated")
				{	x <- seq(pl[[2]]$threshold,max(data[[2]]))
					y <- 1 - cumsum(ddiscpowerexp(x=x,exponent=pl[[2]]$exponent,rate=pl[[2]]$rate,threshold=pl[[2]]$threshold))
					lines(x, y, col="BLACK", lty=2)
				}
				else if(laws[paste0(names(data)[i],"-",meas,if(wt!="none") paste0("-",wt) else "")]=="good")
					lines(pl[[i]], col="BLACK", lty=2)
			}
			dev.off()
		}
		
		# correlation between degree and number of occurrences
		pear.cor <- cor(data[[1]],sce.nbr[unfilt.idx], method="pearson")
		kend.cor <- cor(data[[1]],sce.nbr[unfilt.idx], method="kendall")
		spear.cor <- cor(data[[1]],sce.nbr[unfilt.idx], method="spearman")
		tlog(6,"Correlation between unfiltered degree and scene numbers: Pearson=",pear.cor,"Kendall=",kend.cor," Spearman=",spear.cor)
		file <- get.path.stats.topo(net.type="static", mode="scenes", meas.name=MEAS_MULTI_NODES, weights=wt, filtered="unfiltered", suf=paste0(meas,"_vs_scenes_correlation"))
		tlog(8,"Recording in file \"",file,"\"")
		tab <- data.frame(pear.cor, kend.cor, spear.cor)
		colnames(tab) <- c("Pearson", "Kendall", "Spearman")
		write.csv(x=tab, file=paste0(file,".csv"), fileEncoding="UTF-8", row.names=FALSE)
		#
		pear.cor <- cor(data[[2]],sce.nbr[idx.keep][filt.idx], method="pearson")
		kend.cor <- cor(data[[2]],sce.nbr[idx.keep][filt.idx], method="kendall")
		spear.cor <- cor(data[[2]],sce.nbr[idx.keep][filt.idx], method="spearman")
		tlog(6,"Correlation between filtered degree and scene numbers: Pearson=",pear.cor,"Kendall=",kend.cor," Spearman=",spear.cor)
		file <- get.path.stats.topo(net.type="static", mode="scenes", meas.name=MEAS_MULTI_NODES, weights=wt, filtered="filtered", suf=paste0(meas,"_vs_scenes_correlation"))
		tlog(8,"Recording in file \"",file,"\"")
		tab <- data.frame(pear.cor, kend.cor, spear.cor)
		colnames(tab) <- c("Pearson", "Kendall", "Spearman")
		write.csv(x=tab, file=paste0(file,".csv"), fileEncoding="UTF-8", row.names=FALSE)
	}
}




###############################################################################
# end logging
tlog(0,"Process complete")
end.rec.log()
